"""initial

Revision ID: 62a503e28b94
Revises: 
Create Date: 2024-03-06 23:55:43.135125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a503e28b94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beam__inform',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_name', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.String(length=140), nullable=True),
    sa.Column('save_path', sa.String(length=140), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beam__inform')
    # ### end Alembic commands ###
