"""add filename

Revision ID: 85639d478de0
Revises: 62a503e28b94
Create Date: 2024-04-05 02:23:58.427111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85639d478de0'
down_revision = '62a503e28b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beam__inform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_filename', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beam__inform', schema=None) as batch_op:
        batch_op.drop_column('upload_filename')

    # ### end Alembic commands ###
